"""create_initial_document_page_chunk_tables

Revision ID: 3f646c4705d5
Revises: 
Create Date: 2026-09-29 22:42:10.139945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f646c4705d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('pages',
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_number >= 1', name='ck_pages_page_number_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_pages_document_page_number')
    )
    op.create_index(op.f('ix_pages_document_id'), 'pages', ['document_id'], unique=False)
    op.create_index('ix_pages_document_id_page_number', 'pages', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_pages_page_id'), 'pages', ['page_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_chunks_chunk_index_non_negative'),
    sa.CheckConstraint('page_number >= 1', name='ck_chunks_page_number_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'page_number', 'chunk_index', name='uq_chunks_document_page_chunk')
    )
    op.create_index(op.f('ix_chunks_chunk_id'), 'chunks', ['chunk_id'], unique=False)
    op.create_index('ix_chunks_doc_page_idx', 'chunks', ['document_id', 'page_number', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_document_page', 'chunks', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_index('ix_chunks_document_page', table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index('ix_chunks_doc_page_idx', table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_pages_page_id'), table_name='pages')
    op.drop_index('ix_pages_document_id_page_number', table_name='pages')
    op.drop_index(op.f('ix_pages_document_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
